### ISSUE TITLE
[Bug] <App manager> Android 12 中, 作为 Profile owner 时调用"禁止用户控制"功能将导致闪退

### ISSUE THREAD

**Issue by MinoriceOwO** [BinTianqi/OwnDroid#12]
## 描述问题 / Describe the issue
当 OwnDroid 作为 Profile owner 被激活时, 如果尝试调用"应用管理"下的"禁止用户控制"功能 (无论目标应用包名设置为何) 将会导致 OwnDroid 意外闪退。

## 复现步骤 / Reproducing steps
1. 为 OwnDroid 授予 Device admin 与 Profile owner (工作资料/机主/其他用户均可) 权限。
2. 打开 OwnDroid。
3. 进入"应用管理"。
4. 输入一个已安装应用的包名, 单击下方"禁止用户控制"选项。
5. OwnDroid 意外停止运行。

## 预期结果 / Expected result
根据错误日志内容分析, 似乎 Profile owner 下不支持此功能。此时 OwnDroid 应展现一个友好提示, 或直接隐藏该选项。

## 错误日志 / Logs
```
java.lang.SecurityException: Calling identity is not authorized
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.admin.IDevicePolicyManager$Stub$Proxy.getUserControlDisabledPackages(IDevicePolicyManager.java:16106)
	at android.app.admin.DevicePolicyManager.getUserControlDisabledPackages(DevicePolicyManager.java:13462)
	at com.bintianqi.owndroid.dpm.ManagedProfileKt$$ExternalSyntheticApiModelOutline0.m(SourceFile:5)
	at com.bintianqi.owndroid.dpm.ApplicationManageKt.access$UserCtrlDisabledPkg(SourceFile:210)
	at com.bintianqi.owndroid.dpm.ApplicationManageKt$ApplicationManage$2$1$5$2.invoke(SourceFile:24)
	at com.bintianqi.owndroid.dpm.ApplicationManageKt$ApplicationManage$2$1$5$2.invoke(SourceFile:50)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:31)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:11)
	at androidx.compose.material3.ButtonKt$Button$3$1.invoke(SourceFile:43)
	at androidx.compose.material3.ButtonKt$Button$3$1.invoke(SourceFile:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
	at androidx.compose.ui.Modifier$-CC.m(SourceFile:47)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:76)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SourceFile:162)
	at kotlin.TuplesKt.access$SaveableStateProvider(SourceFile:92)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(SourceFile:4)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(SourceFile:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
	at androidx.compose.ui.Modifier$-CC.m(SourceFile:47)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:28)
	at kotlin.TuplesKt.LocalOwnersProvider(SourceFile:60)
	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(SourceFile:432)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:31)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:11)
	at androidx.compose.foundation.text.TextFieldCursorKt$cursor$1.invoke(SourceFile:279)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:21)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:10)
	at kotlin.TuplesKt.AnimatedEnterExitImpl(SourceFile:840)
	at com.bintianqi.owndroid.PkgSelectorKt$PackageSelector$1.invoke(SourceFile:47)
	at com.bintianqi.owndroid.PkgSelectorKt$PackageSelector$1.invoke(SourceFile:1)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
	at androidx.collection.ArraySetKt.AnimatedContent(SourceFile:1007)
	at kotlin.ResultKt.NavHost(SourceFile:303)
	at kotlin.ResultKt.NavHost(SourceFile:49)
	at com.bintianqi.owndroid.dpm.SystemManagerKt$CaCert$2$2.invoke(SourceFile:496)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:21)
	at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:13)
	at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:4)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:518)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:137)
	at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:157)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:29)
	at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:34)
	at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:100)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:518)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1118)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:854)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8001)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@dd0417b, androidx.compose.ui.platform.MotionDurationScaleImpl@5c18b98, StandaloneCoroutine{Cancelling}@b80eff1, AndroidUiDispatcher@467c7d6]
```

**Comment by MinoriceOwO** [comment]
大半夜还在看 Issue 啊...

早睡。

![](https://s2.loli.net/2024/04/22/iGWnqryPehA6Ms9.png)

**Comment by BinTianqi** [comment]
奇怪

谷歌说profile owner也能用: 

https://developer.android.com/reference/kotlin/android/app/admin/DevicePolicyManager#setusercontroldisabledpackages

**Comment by MinoriceOwO** [comment]
> 奇怪
> 
> 谷歌说profile owner也能用:
> 
> https://developer.android.com/reference/kotlin/android/app/admin/DevicePolicyManager#setusercontroldisabledpackages
> 
> （好久没看过谷歌网站上的文档了，一直都在看AndroidStudio里面的快速文档）

看文档好像还真是, `setUserControlDisabledPackages` 和 `getUserControlDisabledPackages` 两个理论上 Profile owner 都能调用。

但是想起了昨天看到 canyie 个人频道里的《Android 开发文档离谱错误一览》, 感觉好像也不奇怪了... (确信

或者说再试试看复现一下, 看看是不是所有设备都会发生这个问题...? 发生闪退的设备型号是 `LG V50S`, 现在手上的 `OnePlus Ace Pro` 主用机因为已经激活了 Device owner 所以没有测试, 也有可能是设备问题。

**Comment by BinTianqi** [comment]
我一直都是在安卓14上测试这个app的，无论是模拟器还是我自己的手机。所以我也没发现什么问题

**Comment by BinTianqi** [comment]
> 好像找到问题了。调用 getUserControlDisabledPackages 似乎需要一个权限, 名为 [MANAGE_DEVICE_POLICY_APPS_CONTROL](https://developer.android.com/reference/android/Manifest.permission#MANAGE_DEVICE_POLICY_APPS_CONTROL), 这个权限至少需要 API Level `34`。
> 
> 我看到 OwnDroid 在清单文件里申请了这项权限, 会不会是因为这项权限在低于 API Level 34 的版本中不受支持而导致的崩溃?
> 
> 如果真的是这个原因的话, OwnDroid 可能后续还得添加安卓版本检测, 如果 API 版本过低就隐藏部分功能或者改变实现方案。

[我看了看，应该不需要这个权限](https://developer.android.google.cn/reference/kotlin/android/app/admin/DevicePolicyManager#setusercontroldisabledpackages)

> device or profile owner **_or_** holders of the permission android.Manifest.permission.MANAGE_DEVICE_POLICY_APPS_CONTROL

已经是profile owner应该就不需要这个权限了

（这种特殊权限是留给系统应用用的，需要在`/system/etc/default-permissions`里面放一个xml）

**Comment by MinoriceOwO** [comment]
> [我看了看，应该不需要这个权限](https://developer.android.google.cn/reference/kotlin/android/app/admin/DevicePolicyManager#setusercontroldisabledpackages)
> 
> > device or profile owner **_or_** holders of the permission android.Manifest.permission.MANAGE_DEVICE_POLICY_APPS_CONTROL
> 
> 已经是profile owner应该就不需要这个权限了
> 
> （这种特殊权限是留给系统应用用的，需要在`/system/etc/default-permissions`里面放一个xml）

我当时也看到那个 or 了, 但是感觉除了这个好像没有其他可能性了。身边也没有其他 30 ≤ API Level < 34 的设备, 确认不了是否在这个 API Level 范围内都会出现问题。

**Comment by BinTianqi** [comment]
## 没问题啊（主用户）

![Screenshot_20240422_205445](https://github.com/BinTianqi/OwnDroid/assets/146811279/92561c52-19df-4128-9d46-b8207dd1541a)

**Comment by MinoriceOwO** [comment]
> ## 没问题啊（主用户）

啊? 嘶... 那难道是我设备问题...?
当时测试的时候主用户和工作资料的 Profile owner 都会崩溃。

**Comment by BinTianqi** [comment]
工作资料也测了，没问题

（这种东西用的人特别少，说不定是lg搞的鬼）

**Comment by MinoriceOwO** [comment]
> 工作资料也测了，没问题
> 
> （这种东西用的人特别少，说不定是lg搞的鬼）

好像很有可能... 我再开个 AVD 测试一下。

**Comment by MinoriceOwO** [comment]
> 好像很有可能... 我再开个 AVD 测试一下。

AVD 没开起来, 刚刚才反应过来虚拟机在没有 VT 的云服务器上约等于跑不起来, 身边也没有实体的桌面设备。

等这周末我看看有空再测试一下吧, 这个 Issue 我就先关了。

**Comment by BinTianqi** [comment]
这难道是安卓12特有的问题？

**Comment by MinoriceOwO** [comment]
不是特别理解, 刚刚测试了一下, Android 12 下如果是 Device owner 功能就完全是正常的。

Profile owner 下尝试改了下清单值, 申请了一个 INTERACT_ACROSS_PROFILES 权限, 再把 OwnDroid 丢到系统分区里面, 依然无济于事。该 `SecurityException` 还是 `SecurityException`。看不懂问题出在哪里。

**Comment by BinTianqi** [comment]
直接在安卓12上隐藏这个功能吧

> It's Google's fault

**Comment by MinoriceOwO** [comment]
经过测试, 在 Android 11 (API 30) 与 Android 12L (API 32) 的 Profile owner 工作状态下也同样存在此问题。

![A11 Issue.png](https://s2.loli.net/2024/04/27/p4gO1vmuQyYsrBt.png)

![A12L Issue.png](https://s2.loli.net/2024/04/27/XjbNwA2TLiWuOh9.png)
