### ISSUE TITLE
Crash on System manager Options

### ISSUE THREAD

**Issue by shuvashish76** [BinTianqi/OwnDroid#67]
App crashes when I click on System manager > Options

```
FATAL EXCEPTION: main
Process: com.bintianqi.owndroid, PID: 11801
java.lang.SecurityException: Admin ComponentInfo{com.bintianqi.owndroid/com.bintianqi.owndroid.Receiver} does not own the device
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.admin.IDevicePolicyManager$Stub$Proxy.isBackupServiceEnabled(IDevicePolicyManager.java:9721)
	at android.app.admin.DevicePolicyManager.isBackupServiceEnabled(DevicePolicyManager.java:8842)
	at x1.V0.v(SourceFile:1)
	at x1.u0.c(SourceFile:176)
	at y.E.i(SourceFile:251)
	at x1.i2.q(SourceFile:736)
	at x1.g0.k(SourceFile:528)
	at Q.b.e(SourceFile:44)
	at Q.b.k(SourceFile:9)
	at E.z.m(SourceFile:390)
	at Q.b.m(SourceFile:52)
	at I.d.a(SourceFile:222)
	at R.h.f(SourceFile:162)
	at androidx.activity.result.d.q(SourceFile:90)
	at androidx.navigation.compose.o.m(SourceFile:75)
	at Q.b.m(SourceFile:52)
	at I.d.b(SourceFile:150)
	at androidx.activity.result.d.l(SourceFile:51)
	at androidx.navigation.compose.t.k(SourceFile:600)
	at Q.b.e(SourceFile:44)
	at Q.b.k(SourceFile:9)
	at C.y0.l(SourceFile:268)
	at Q.b.d(SourceFile:44)
	at Q.b.l(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1287)
	at r.c.m(SourceFile:273)
	at Q.b.m(SourceFile:52)
	at androidx.activity.result.d.i(SourceFile:927)
	at androidx.activity.result.d.n(SourceFile:1782)
	at androidx.navigation.compose.v.m(SourceFile:114)
	at I.r.M(SourceFile:517)
	at I.r.T(SourceFile:137)
	at I.r.q(SourceFile:161)
	at I.r.K(SourceFile:29)
	at I.x.v(SourceFile:35)
	at I.z0.t(SourceFile:123)
	at I.x0.n(SourceFile:513)
	at I.D.doFrame(SourceFile:14)
	at androidx.compose.ui.platform.V.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: d2.f: [I.m0@50051ea, androidx.compose.ui.platform.u0@f145cdb, i0{Cancelling}@c587378, W@ba7ea51]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.devicepolicy.DevicePolicyManagerService.getActiveAdminForCallerLocked(DevicePolicyManagerService.java:2603)
	at com.android.server.devicepolicy.DevicePolicyManagerService.isBackupServiceEnabled(DevicePolicyManagerService.java:12003)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3764)
	at android.os.Binder.execTransact(Binder.java:731)
```
App version: 5.6
Android: 9
Model: Lenovo Tab4 8 plus

Profile owner permission is already given
> `dpm set-profile-owner com.bintianqi.owndroid/com.bintianqi.owndroid.Receiver`

**Comment by BinTianqi** [comment]
This bug should be fixed in the latest CI version. [Download  here](https://github.com/BinTianqi/OwnDroid/actions/runs/10381536207/artifacts/1809736691).

If this issue persist, please download the [latest debug CI version](https://github.com/BinTianqi/OwnDroid/actions/runs/10381536207/artifacts/1809736620), reproduce it and send log to here. (Code of release version is obfuscated and I can't locate the issue from log)
