### ISSUE TITLE
Cl版>系统>安全日志打开闪退

### ISSUE THREAD

**Issue by LiJiu-gfgfv** [BinTianqi/OwnDroid#87]
https://github.com/user-attachments/assets/dadafac6-5552-44f9-9b24-a5531b9c52f7

**Comment by BinTianqi** [comment]
我的手机上打开安全日志不会崩溃

发一下崩溃日志吧（可以用[LogFox](https://github.com/F0x1d/LogFox/releases)抓日志）

**Comment by LiJiu-gfgfv** [comment]
> 我的手机上打开安全日志不会崩溃
> 
> 发一下崩溃日志吧（可以用[LogFox](https://github.com/F0x1d/LogFox/releases)抓日志）

是这样的
FATAL EXCEPTION: main
Process: com.bintianqi.owndroid, PID: 10935
java.lang.IllegalArgumentException: Navigation destination that matches route SecurityLogging cannot be found in the navigation graph f(0x0) startDestination={h(0x2a2baabb) route=HomePage}
	at M1.B.m(SourceFile:110)
	at V1.E1.d(SourceFile:144)
	at V.p0.k(SourceFile:168)
	at y.D0.n(SourceFile:132)
	at i2.a.r(SourceFile:9)
	at B2.y.r(SourceFile:81)
	at B2.f.p(SourceFile:105)
	at B2.f.C(SourceFile:33)
	at B2.f.r(SourceFile:17)
	at A0.K.v0(SourceFile:51)
	at A0.K.R(SourceFile:31)
	at w.v.R(SourceFile:105)
	at A0.j.h(SourceFile:157)
	at A0.j.h(SourceFile:136)
	at A0.j.h(SourceFile:136)
	at A0.j.h(SourceFile:136)
	at A0.j.h(SourceFile:136)
	at A0.f.i(SourceFile:36)
	at A0.A.f(SourceFile:141)
	at H0.z.I(SourceFile:81)
	at H0.z.o(SourceFile:383)
	at H0.z.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1911)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4256)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
	at android.view.View.dispatchPointerEvent(View.java:14940)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6932)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6703)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6168)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6230)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6191)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6365)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6199)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6422)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6172)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6230)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6191)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6199)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6172)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9301)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9241)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9192)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9455)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:179)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
	Suppressed: G2.f: [H0.L0@c0a84d0, V.g@dd21cc9, l0{Cancelling}@3b1afce, j0@d8cceef]

**Comment by BinTianqi** [comment]
试试最新的CI版
https://github.com/BinTianqi/OwnDroid/actions/runs/12533011381

**Comment by LiJiu-gfgfv** [comment]
> 试试最新的CI版
> https://github.com/BinTianqi/OwnDroid/actions/runs/12533011381

正常了，能不能加一下QQ703251609

**Comment by BinTianqi** [comment]
> 正常了，能不能加一下QQ703251609

关于OwnDroid的事直接说，如果是别的事，可以加我的[Telegram](https://t.me/bintianqi)，qq我用得很少

**Comment by LiJiu-gfgfv** [comment]
好吧

**Comment by LiJiu-gfgfv** [comment]
用了LogFox后发现...![Screenshot_2025-01-06-00-28-49-47_3640f6bcd0ec72328b9113e5106e374f.jpg](https://github.com/user-attachments/assets/67e74748-2c38-4b35-8e8f-3e7c88ca3a6c)
